nameOverride: bookshelf

backend:
  image: ghcr.io/pirobeastie/bookshelf-backend
  tag: latest
  replicas: 2
  port: 8000

frontend:
  image: ghcr.io/pirobeastie/bookshelf-frontend
  tag: latest
  replicas: 2
  port: 8080

imagePullPolicy: IfNotPresent
imagePullSecrets: []

postgres:
  enabled: true
  image: postgres:16-alpine
  database: bookshelf
  username: bookshelf
  password: bookshelf
  storage: 1Gi

ingress:
  enabled: true
  className: nginx
  host: bookshelf.local

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  backend:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 384Mi}
  frontend:
    requests: {cpu: 10m, memory: 32Mi}
    limits: {cpu: 200m, memory: 128Mi}
